### ISSUE TITLE
Setup Style CI

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#54]
## Goal

Untuk mempersatukan gaya kode di proyek ini, kita akan menerapkan pengecekan styleci.io di setiap push commit ke github (baik branch master maupun pull request). Ini untuk mempermudah dan menghemat waktu reviewer sehingga bisa fokus pada review fitur dan potensi bug.

Link: https://styleci.io

Kita pakai styleci.io karena untuk proyek opensource akan selalu gratis.

## Checklist

- [x] ~Setup StyleCI~ batal
- [x] Setup laravel pint
- [x] Buat pint.json untuk preset dan rule pengecekan code style
- [x] Menggunakan preset laravel
- [x] Setup github action untuk auto check pada pull request

### Notes

- ~Dokumentasi: https://docs.styleci.io/~
- ~Contoh: https://github.com/nafiesl/free-pmo/blob/master/.styleci.yml~
- Dokumentasi: https://laravel.com/docs/11.x/pint

**Comment by andriawan** [comment]
Mas @nafiesl saya ada saran. Untuk konsistensi style, proyek ini bisa menggunakan [Laravel pint ](https://laravel.com/docs/11.x/pint)+ github actions. Alasanya adalah agar memudahkan pengembangan jika masih dalam satu platform github. Saya yakin karena project ini open source, penggunaan github actions bisa tanpa batas.

Saya pernah menerapkan autoformat laravel pint dalam project tertentu. Ini adalah contoh konfigurasinya

```
name: Fix Code Style with Laravel Pint
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  phplint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel
 
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Laravel Pint Auto Fix
          skip_fetch: true
```
